/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the RoutingPolicyRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoutingPolicyRule{}

// RoutingPolicyRule Adds support for custom fields and tags.
type RoutingPolicyRule struct {
	Id                   int32                   `json:"id"`
	Index                int32                   `json:"index"`
	Display              string                  `json:"display"`
	Action               CommunityListRuleAction `json:"action"`
	MatchIpAddress       []*int32                `json:"match_ip_address,omitempty"`
	RoutingPolicy        NestedRoutingPolicy     `json:"routing_policy"`
	MatchCommunity       []*int32                `json:"match_community,omitempty"`
	MatchCustom          interface{}             `json:"match_custom,omitempty"`
	SetActions           interface{}             `json:"set_actions,omitempty"`
	MatchIpv6Address     []int32                 `json:"match_ipv6_address,omitempty"`
	Description          *string                 `json:"description,omitempty"`
	Tags                 []NestedTag             `json:"tags,omitempty"`
	CustomFields         map[string]interface{}  `json:"custom_fields,omitempty"`
	Comments             *string                 `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RoutingPolicyRule RoutingPolicyRule

// NewRoutingPolicyRule instantiates a new RoutingPolicyRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoutingPolicyRule(id int32, index int32, display string, action CommunityListRuleAction, routingPolicy NestedRoutingPolicy) *RoutingPolicyRule {
	this := RoutingPolicyRule{}
	this.Id = id
	this.Index = index
	this.Display = display
	this.Action = action
	this.RoutingPolicy = routingPolicy
	return &this
}

// NewRoutingPolicyRuleWithDefaults instantiates a new RoutingPolicyRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoutingPolicyRuleWithDefaults() *RoutingPolicyRule {
	this := RoutingPolicyRule{}
	return &this
}

// GetId returns the Id field value
func (o *RoutingPolicyRule) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RoutingPolicyRule) SetId(v int32) {
	o.Id = v
}

// GetIndex returns the Index field value
func (o *RoutingPolicyRule) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *RoutingPolicyRule) SetIndex(v int32) {
	o.Index = v
}

// GetDisplay returns the Display field value
func (o *RoutingPolicyRule) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *RoutingPolicyRule) SetDisplay(v string) {
	o.Display = v
}

// GetAction returns the Action field value
func (o *RoutingPolicyRule) GetAction() CommunityListRuleAction {
	if o == nil {
		var ret CommunityListRuleAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetActionOk() (*CommunityListRuleAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *RoutingPolicyRule) SetAction(v CommunityListRuleAction) {
	o.Action = v
}

// GetMatchIpAddress returns the MatchIpAddress field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetMatchIpAddress() []*int32 {
	if o == nil || IsNil(o.MatchIpAddress) {
		var ret []*int32
		return ret
	}
	return o.MatchIpAddress
}

// GetMatchIpAddressOk returns a tuple with the MatchIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetMatchIpAddressOk() ([]*int32, bool) {
	if o == nil || IsNil(o.MatchIpAddress) {
		return nil, false
	}
	return o.MatchIpAddress, true
}

// HasMatchIpAddress returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasMatchIpAddress() bool {
	if o != nil && !IsNil(o.MatchIpAddress) {
		return true
	}

	return false
}

// SetMatchIpAddress gets a reference to the given []*int32 and assigns it to the MatchIpAddress field.
func (o *RoutingPolicyRule) SetMatchIpAddress(v []*int32) {
	o.MatchIpAddress = v
}

// GetRoutingPolicy returns the RoutingPolicy field value
func (o *RoutingPolicyRule) GetRoutingPolicy() NestedRoutingPolicy {
	if o == nil {
		var ret NestedRoutingPolicy
		return ret
	}

	return o.RoutingPolicy
}

// GetRoutingPolicyOk returns a tuple with the RoutingPolicy field value
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetRoutingPolicyOk() (*NestedRoutingPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingPolicy, true
}

// SetRoutingPolicy sets field value
func (o *RoutingPolicyRule) SetRoutingPolicy(v NestedRoutingPolicy) {
	o.RoutingPolicy = v
}

// GetMatchCommunity returns the MatchCommunity field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetMatchCommunity() []*int32 {
	if o == nil || IsNil(o.MatchCommunity) {
		var ret []*int32
		return ret
	}
	return o.MatchCommunity
}

// GetMatchCommunityOk returns a tuple with the MatchCommunity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetMatchCommunityOk() ([]*int32, bool) {
	if o == nil || IsNil(o.MatchCommunity) {
		return nil, false
	}
	return o.MatchCommunity, true
}

// HasMatchCommunity returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasMatchCommunity() bool {
	if o != nil && !IsNil(o.MatchCommunity) {
		return true
	}

	return false
}

// SetMatchCommunity gets a reference to the given []*int32 and assigns it to the MatchCommunity field.
func (o *RoutingPolicyRule) SetMatchCommunity(v []*int32) {
	o.MatchCommunity = v
}

// GetMatchCustom returns the MatchCustom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoutingPolicyRule) GetMatchCustom() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MatchCustom
}

// GetMatchCustomOk returns a tuple with the MatchCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoutingPolicyRule) GetMatchCustomOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MatchCustom) {
		return nil, false
	}
	return &o.MatchCustom, true
}

// HasMatchCustom returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasMatchCustom() bool {
	if o != nil && !IsNil(o.MatchCustom) {
		return true
	}

	return false
}

// SetMatchCustom gets a reference to the given interface{} and assigns it to the MatchCustom field.
func (o *RoutingPolicyRule) SetMatchCustom(v interface{}) {
	o.MatchCustom = v
}

// GetSetActions returns the SetActions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RoutingPolicyRule) GetSetActions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SetActions
}

// GetSetActionsOk returns a tuple with the SetActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RoutingPolicyRule) GetSetActionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SetActions) {
		return nil, false
	}
	return &o.SetActions, true
}

// HasSetActions returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasSetActions() bool {
	if o != nil && !IsNil(o.SetActions) {
		return true
	}

	return false
}

// SetSetActions gets a reference to the given interface{} and assigns it to the SetActions field.
func (o *RoutingPolicyRule) SetSetActions(v interface{}) {
	o.SetActions = v
}

// GetMatchIpv6Address returns the MatchIpv6Address field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetMatchIpv6Address() []int32 {
	if o == nil || IsNil(o.MatchIpv6Address) {
		var ret []int32
		return ret
	}
	return o.MatchIpv6Address
}

// GetMatchIpv6AddressOk returns a tuple with the MatchIpv6Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetMatchIpv6AddressOk() ([]int32, bool) {
	if o == nil || IsNil(o.MatchIpv6Address) {
		return nil, false
	}
	return o.MatchIpv6Address, true
}

// HasMatchIpv6Address returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasMatchIpv6Address() bool {
	if o != nil && !IsNil(o.MatchIpv6Address) {
		return true
	}

	return false
}

// SetMatchIpv6Address gets a reference to the given []int32 and assigns it to the MatchIpv6Address field.
func (o *RoutingPolicyRule) SetMatchIpv6Address(v []int32) {
	o.MatchIpv6Address = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *RoutingPolicyRule) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetTags() []NestedTag {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTag
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetTagsOk() ([]NestedTag, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTag and assigns it to the Tags field.
func (o *RoutingPolicyRule) SetTags(v []NestedTag) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *RoutingPolicyRule) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *RoutingPolicyRule) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoutingPolicyRule) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *RoutingPolicyRule) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *RoutingPolicyRule) SetComments(v string) {
	o.Comments = &v
}

func (o RoutingPolicyRule) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoutingPolicyRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["index"] = o.Index
	toSerialize["display"] = o.Display
	toSerialize["action"] = o.Action
	if !IsNil(o.MatchIpAddress) {
		toSerialize["match_ip_address"] = o.MatchIpAddress
	}
	toSerialize["routing_policy"] = o.RoutingPolicy
	if !IsNil(o.MatchCommunity) {
		toSerialize["match_community"] = o.MatchCommunity
	}
	if o.MatchCustom != nil {
		toSerialize["match_custom"] = o.MatchCustom
	}
	if o.SetActions != nil {
		toSerialize["set_actions"] = o.SetActions
	}
	if !IsNil(o.MatchIpv6Address) {
		toSerialize["match_ipv6_address"] = o.MatchIpv6Address
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RoutingPolicyRule) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"index",
		"display",
		"action",
		"routing_policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRoutingPolicyRule := _RoutingPolicyRule{}

	err = json.Unmarshal(data, &varRoutingPolicyRule)

	if err != nil {
		return err
	}

	*o = RoutingPolicyRule(varRoutingPolicyRule)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "index")
		delete(additionalProperties, "display")
		delete(additionalProperties, "action")
		delete(additionalProperties, "match_ip_address")
		delete(additionalProperties, "routing_policy")
		delete(additionalProperties, "match_community")
		delete(additionalProperties, "match_custom")
		delete(additionalProperties, "set_actions")
		delete(additionalProperties, "match_ipv6_address")
		delete(additionalProperties, "description")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRoutingPolicyRule struct {
	value *RoutingPolicyRule
	isSet bool
}

func (v NullableRoutingPolicyRule) Get() *RoutingPolicyRule {
	return v.value
}

func (v *NullableRoutingPolicyRule) Set(val *RoutingPolicyRule) {
	v.value = val
	v.isSet = true
}

func (v NullableRoutingPolicyRule) IsSet() bool {
	return v.isSet
}

func (v *NullableRoutingPolicyRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoutingPolicyRule(val *RoutingPolicyRule) *NullableRoutingPolicyRule {
	return &NullableRoutingPolicyRule{value: val, isSet: true}
}

func (v NullableRoutingPolicyRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoutingPolicyRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
