/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedBGPPeerGroup type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedBGPPeerGroup{}

// NestedBGPPeerGroup Represents an object related through a ForeignKey field. On write, it accepts a primary key (PK) value or a dictionary of attributes which can be used to uniquely identify the related object. This class should be subclassed to return a full representation of the related object on read.
type NestedBGPPeerGroup struct {
	Id                   int32   `json:"id"`
	Display              string  `json:"display"`
	Url                  string  `json:"url"`
	Name                 string  `json:"name"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NestedBGPPeerGroup NestedBGPPeerGroup

// NewNestedBGPPeerGroup instantiates a new NestedBGPPeerGroup object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedBGPPeerGroup(id int32, display string, url string, name string) *NestedBGPPeerGroup {
	this := NestedBGPPeerGroup{}
	this.Id = id
	this.Display = display
	this.Url = url
	this.Name = name
	return &this
}

// NewNestedBGPPeerGroupWithDefaults instantiates a new NestedBGPPeerGroup object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedBGPPeerGroupWithDefaults() *NestedBGPPeerGroup {
	this := NestedBGPPeerGroup{}
	return &this
}

// GetId returns the Id field value
func (o *NestedBGPPeerGroup) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *NestedBGPPeerGroup) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *NestedBGPPeerGroup) SetId(v int32) {
	o.Id = v
}

// GetDisplay returns the Display field value
func (o *NestedBGPPeerGroup) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *NestedBGPPeerGroup) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *NestedBGPPeerGroup) SetDisplay(v string) {
	o.Display = v
}

// GetUrl returns the Url field value
func (o *NestedBGPPeerGroup) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NestedBGPPeerGroup) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NestedBGPPeerGroup) SetUrl(v string) {
	o.Url = v
}

// GetName returns the Name field value
func (o *NestedBGPPeerGroup) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NestedBGPPeerGroup) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NestedBGPPeerGroup) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *NestedBGPPeerGroup) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedBGPPeerGroup) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *NestedBGPPeerGroup) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *NestedBGPPeerGroup) SetDescription(v string) {
	o.Description = &v
}

func (o NestedBGPPeerGroup) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedBGPPeerGroup) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["display"] = o.Display
	toSerialize["url"] = o.Url
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedBGPPeerGroup) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"display",
		"url",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNestedBGPPeerGroup := _NestedBGPPeerGroup{}

	err = json.Unmarshal(data, &varNestedBGPPeerGroup)

	if err != nil {
		return err
	}

	*o = NestedBGPPeerGroup(varNestedBGPPeerGroup)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "display")
		delete(additionalProperties, "url")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedBGPPeerGroup struct {
	value *NestedBGPPeerGroup
	isSet bool
}

func (v NullableNestedBGPPeerGroup) Get() *NestedBGPPeerGroup {
	return v.value
}

func (v *NullableNestedBGPPeerGroup) Set(val *NestedBGPPeerGroup) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedBGPPeerGroup) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedBGPPeerGroup) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedBGPPeerGroup(val *NestedBGPPeerGroup) *NullableNestedBGPPeerGroup {
	return &NullableNestedBGPPeerGroup{value: val, isSet: true}
}

func (v NullableNestedBGPPeerGroup) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedBGPPeerGroup) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
