/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedWritableAssetRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedWritableAssetRequest{}

// PatchedWritableAssetRequest Adds support for custom fields and tags.
type PatchedWritableAssetRequest struct {
	// Can be used to quickly identify a particular asset
	Name *string `json:"name,omitempty"`
	// Identifier assigned by owner
	AssetTag NullableString `json:"asset_tag,omitempty"`
	// Identifier assigned by manufacturer
	Serial            NullableString `json:"serial,omitempty"`
	Status            *AssetStatus   `json:"status,omitempty"`
	DeviceType        NullableInt32  `json:"device_type,omitempty"`
	Device            NullableInt32  `json:"device,omitempty"`
	ModuleType        NullableInt32  `json:"module_type,omitempty"`
	Module            NullableInt32  `json:"module,omitempty"`
	InventoryitemType NullableInt32  `json:"inventoryitem_type,omitempty"`
	Inventoryitem     NullableInt32  `json:"inventoryitem,omitempty"`
	// Tenant using this asset
	Tenant NullableInt32 `json:"tenant,omitempty"`
	// Contact using this asset
	Contact NullableInt32 `json:"contact,omitempty"`
	// Where is this asset stored when not in use
	StorageLocation NullableInt32 `json:"storage_location,omitempty"`
	// Who owns this asset
	Owner NullableInt32 `json:"owner,omitempty"`
	// Delivery this asset was part of
	Delivery NullableInt32 `json:"delivery,omitempty"`
	// Purchase through which this asset was purchased
	Purchase NullableInt32 `json:"purchase,omitempty"`
	// First date warranty for this asset is valid
	WarrantyStart NullableString `json:"warranty_start,omitempty"`
	// Last date warranty for this asset is valid
	WarrantyEnd          NullableString         `json:"warranty_end,omitempty"`
	Comments             *string                `json:"comments,omitempty"`
	Tags                 []NestedTagRequest     `json:"tags,omitempty"`
	CustomFields         map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedWritableAssetRequest PatchedWritableAssetRequest

// NewPatchedWritableAssetRequest instantiates a new PatchedWritableAssetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedWritableAssetRequest() *PatchedWritableAssetRequest {
	this := PatchedWritableAssetRequest{}
	return &this
}

// NewPatchedWritableAssetRequestWithDefaults instantiates a new PatchedWritableAssetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedWritableAssetRequestWithDefaults() *PatchedWritableAssetRequest {
	this := PatchedWritableAssetRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedWritableAssetRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableAssetRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedWritableAssetRequest) SetName(v string) {
	o.Name = &v
}

// GetAssetTag returns the AssetTag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetAssetTag() string {
	if o == nil || IsNil(o.AssetTag.Get()) {
		var ret string
		return ret
	}
	return *o.AssetTag.Get()
}

// GetAssetTagOk returns a tuple with the AssetTag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetAssetTagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AssetTag.Get(), o.AssetTag.IsSet()
}

// HasAssetTag returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasAssetTag() bool {
	if o != nil && o.AssetTag.IsSet() {
		return true
	}

	return false
}

// SetAssetTag gets a reference to the given NullableString and assigns it to the AssetTag field.
func (o *PatchedWritableAssetRequest) SetAssetTag(v string) {
	o.AssetTag.Set(&v)
}

// SetAssetTagNil sets the value for AssetTag to be an explicit nil
func (o *PatchedWritableAssetRequest) SetAssetTagNil() {
	o.AssetTag.Set(nil)
}

// UnsetAssetTag ensures that no value is present for AssetTag, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetAssetTag() {
	o.AssetTag.Unset()
}

// GetSerial returns the Serial field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetSerial() string {
	if o == nil || IsNil(o.Serial.Get()) {
		var ret string
		return ret
	}
	return *o.Serial.Get()
}

// GetSerialOk returns a tuple with the Serial field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetSerialOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Serial.Get(), o.Serial.IsSet()
}

// HasSerial returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasSerial() bool {
	if o != nil && o.Serial.IsSet() {
		return true
	}

	return false
}

// SetSerial gets a reference to the given NullableString and assigns it to the Serial field.
func (o *PatchedWritableAssetRequest) SetSerial(v string) {
	o.Serial.Set(&v)
}

// SetSerialNil sets the value for Serial to be an explicit nil
func (o *PatchedWritableAssetRequest) SetSerialNil() {
	o.Serial.Set(nil)
}

// UnsetSerial ensures that no value is present for Serial, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetSerial() {
	o.Serial.Unset()
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *PatchedWritableAssetRequest) GetStatus() AssetStatus {
	if o == nil || IsNil(o.Status) {
		var ret AssetStatus
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableAssetRequest) GetStatusOk() (*AssetStatus, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given AssetStatus and assigns it to the Status field.
func (o *PatchedWritableAssetRequest) SetStatus(v AssetStatus) {
	o.Status = &v
}

// GetDeviceType returns the DeviceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetDeviceType() int32 {
	if o == nil || IsNil(o.DeviceType.Get()) {
		var ret int32
		return ret
	}
	return *o.DeviceType.Get()
}

// GetDeviceTypeOk returns a tuple with the DeviceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetDeviceTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.DeviceType.Get(), o.DeviceType.IsSet()
}

// HasDeviceType returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasDeviceType() bool {
	if o != nil && o.DeviceType.IsSet() {
		return true
	}

	return false
}

// SetDeviceType gets a reference to the given NullableInt32 and assigns it to the DeviceType field.
func (o *PatchedWritableAssetRequest) SetDeviceType(v int32) {
	o.DeviceType.Set(&v)
}

// SetDeviceTypeNil sets the value for DeviceType to be an explicit nil
func (o *PatchedWritableAssetRequest) SetDeviceTypeNil() {
	o.DeviceType.Set(nil)
}

// UnsetDeviceType ensures that no value is present for DeviceType, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetDeviceType() {
	o.DeviceType.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetDevice() int32 {
	if o == nil || IsNil(o.Device.Get()) {
		var ret int32
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetDeviceOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableInt32 and assigns it to the Device field.
func (o *PatchedWritableAssetRequest) SetDevice(v int32) {
	o.Device.Set(&v)
}

// SetDeviceNil sets the value for Device to be an explicit nil
func (o *PatchedWritableAssetRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetDevice() {
	o.Device.Unset()
}

// GetModuleType returns the ModuleType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetModuleType() int32 {
	if o == nil || IsNil(o.ModuleType.Get()) {
		var ret int32
		return ret
	}
	return *o.ModuleType.Get()
}

// GetModuleTypeOk returns a tuple with the ModuleType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetModuleTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ModuleType.Get(), o.ModuleType.IsSet()
}

// HasModuleType returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasModuleType() bool {
	if o != nil && o.ModuleType.IsSet() {
		return true
	}

	return false
}

// SetModuleType gets a reference to the given NullableInt32 and assigns it to the ModuleType field.
func (o *PatchedWritableAssetRequest) SetModuleType(v int32) {
	o.ModuleType.Set(&v)
}

// SetModuleTypeNil sets the value for ModuleType to be an explicit nil
func (o *PatchedWritableAssetRequest) SetModuleTypeNil() {
	o.ModuleType.Set(nil)
}

// UnsetModuleType ensures that no value is present for ModuleType, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetModuleType() {
	o.ModuleType.Unset()
}

// GetModule returns the Module field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetModule() int32 {
	if o == nil || IsNil(o.Module.Get()) {
		var ret int32
		return ret
	}
	return *o.Module.Get()
}

// GetModuleOk returns a tuple with the Module field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetModuleOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Module.Get(), o.Module.IsSet()
}

// HasModule returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasModule() bool {
	if o != nil && o.Module.IsSet() {
		return true
	}

	return false
}

// SetModule gets a reference to the given NullableInt32 and assigns it to the Module field.
func (o *PatchedWritableAssetRequest) SetModule(v int32) {
	o.Module.Set(&v)
}

// SetModuleNil sets the value for Module to be an explicit nil
func (o *PatchedWritableAssetRequest) SetModuleNil() {
	o.Module.Set(nil)
}

// UnsetModule ensures that no value is present for Module, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetModule() {
	o.Module.Unset()
}

// GetInventoryitemType returns the InventoryitemType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetInventoryitemType() int32 {
	if o == nil || IsNil(o.InventoryitemType.Get()) {
		var ret int32
		return ret
	}
	return *o.InventoryitemType.Get()
}

// GetInventoryitemTypeOk returns a tuple with the InventoryitemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetInventoryitemTypeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.InventoryitemType.Get(), o.InventoryitemType.IsSet()
}

// HasInventoryitemType returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasInventoryitemType() bool {
	if o != nil && o.InventoryitemType.IsSet() {
		return true
	}

	return false
}

// SetInventoryitemType gets a reference to the given NullableInt32 and assigns it to the InventoryitemType field.
func (o *PatchedWritableAssetRequest) SetInventoryitemType(v int32) {
	o.InventoryitemType.Set(&v)
}

// SetInventoryitemTypeNil sets the value for InventoryitemType to be an explicit nil
func (o *PatchedWritableAssetRequest) SetInventoryitemTypeNil() {
	o.InventoryitemType.Set(nil)
}

// UnsetInventoryitemType ensures that no value is present for InventoryitemType, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetInventoryitemType() {
	o.InventoryitemType.Unset()
}

// GetInventoryitem returns the Inventoryitem field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetInventoryitem() int32 {
	if o == nil || IsNil(o.Inventoryitem.Get()) {
		var ret int32
		return ret
	}
	return *o.Inventoryitem.Get()
}

// GetInventoryitemOk returns a tuple with the Inventoryitem field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetInventoryitemOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Inventoryitem.Get(), o.Inventoryitem.IsSet()
}

// HasInventoryitem returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasInventoryitem() bool {
	if o != nil && o.Inventoryitem.IsSet() {
		return true
	}

	return false
}

// SetInventoryitem gets a reference to the given NullableInt32 and assigns it to the Inventoryitem field.
func (o *PatchedWritableAssetRequest) SetInventoryitem(v int32) {
	o.Inventoryitem.Set(&v)
}

// SetInventoryitemNil sets the value for Inventoryitem to be an explicit nil
func (o *PatchedWritableAssetRequest) SetInventoryitemNil() {
	o.Inventoryitem.Set(nil)
}

// UnsetInventoryitem ensures that no value is present for Inventoryitem, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetInventoryitem() {
	o.Inventoryitem.Unset()
}

// GetTenant returns the Tenant field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetTenant() int32 {
	if o == nil || IsNil(o.Tenant.Get()) {
		var ret int32
		return ret
	}
	return *o.Tenant.Get()
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetTenantOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Tenant.Get(), o.Tenant.IsSet()
}

// HasTenant returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasTenant() bool {
	if o != nil && o.Tenant.IsSet() {
		return true
	}

	return false
}

// SetTenant gets a reference to the given NullableInt32 and assigns it to the Tenant field.
func (o *PatchedWritableAssetRequest) SetTenant(v int32) {
	o.Tenant.Set(&v)
}

// SetTenantNil sets the value for Tenant to be an explicit nil
func (o *PatchedWritableAssetRequest) SetTenantNil() {
	o.Tenant.Set(nil)
}

// UnsetTenant ensures that no value is present for Tenant, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetTenant() {
	o.Tenant.Unset()
}

// GetContact returns the Contact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetContact() int32 {
	if o == nil || IsNil(o.Contact.Get()) {
		var ret int32
		return ret
	}
	return *o.Contact.Get()
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetContactOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contact.Get(), o.Contact.IsSet()
}

// HasContact returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasContact() bool {
	if o != nil && o.Contact.IsSet() {
		return true
	}

	return false
}

// SetContact gets a reference to the given NullableInt32 and assigns it to the Contact field.
func (o *PatchedWritableAssetRequest) SetContact(v int32) {
	o.Contact.Set(&v)
}

// SetContactNil sets the value for Contact to be an explicit nil
func (o *PatchedWritableAssetRequest) SetContactNil() {
	o.Contact.Set(nil)
}

// UnsetContact ensures that no value is present for Contact, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetContact() {
	o.Contact.Unset()
}

// GetStorageLocation returns the StorageLocation field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetStorageLocation() int32 {
	if o == nil || IsNil(o.StorageLocation.Get()) {
		var ret int32
		return ret
	}
	return *o.StorageLocation.Get()
}

// GetStorageLocationOk returns a tuple with the StorageLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetStorageLocationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageLocation.Get(), o.StorageLocation.IsSet()
}

// HasStorageLocation returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasStorageLocation() bool {
	if o != nil && o.StorageLocation.IsSet() {
		return true
	}

	return false
}

// SetStorageLocation gets a reference to the given NullableInt32 and assigns it to the StorageLocation field.
func (o *PatchedWritableAssetRequest) SetStorageLocation(v int32) {
	o.StorageLocation.Set(&v)
}

// SetStorageLocationNil sets the value for StorageLocation to be an explicit nil
func (o *PatchedWritableAssetRequest) SetStorageLocationNil() {
	o.StorageLocation.Set(nil)
}

// UnsetStorageLocation ensures that no value is present for StorageLocation, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetStorageLocation() {
	o.StorageLocation.Unset()
}

// GetOwner returns the Owner field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetOwner() int32 {
	if o == nil || IsNil(o.Owner.Get()) {
		var ret int32
		return ret
	}
	return *o.Owner.Get()
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetOwnerOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Owner.Get(), o.Owner.IsSet()
}

// HasOwner returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasOwner() bool {
	if o != nil && o.Owner.IsSet() {
		return true
	}

	return false
}

// SetOwner gets a reference to the given NullableInt32 and assigns it to the Owner field.
func (o *PatchedWritableAssetRequest) SetOwner(v int32) {
	o.Owner.Set(&v)
}

// SetOwnerNil sets the value for Owner to be an explicit nil
func (o *PatchedWritableAssetRequest) SetOwnerNil() {
	o.Owner.Set(nil)
}

// UnsetOwner ensures that no value is present for Owner, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetOwner() {
	o.Owner.Unset()
}

// GetDelivery returns the Delivery field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetDelivery() int32 {
	if o == nil || IsNil(o.Delivery.Get()) {
		var ret int32
		return ret
	}
	return *o.Delivery.Get()
}

// GetDeliveryOk returns a tuple with the Delivery field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetDeliveryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Delivery.Get(), o.Delivery.IsSet()
}

// HasDelivery returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasDelivery() bool {
	if o != nil && o.Delivery.IsSet() {
		return true
	}

	return false
}

// SetDelivery gets a reference to the given NullableInt32 and assigns it to the Delivery field.
func (o *PatchedWritableAssetRequest) SetDelivery(v int32) {
	o.Delivery.Set(&v)
}

// SetDeliveryNil sets the value for Delivery to be an explicit nil
func (o *PatchedWritableAssetRequest) SetDeliveryNil() {
	o.Delivery.Set(nil)
}

// UnsetDelivery ensures that no value is present for Delivery, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetDelivery() {
	o.Delivery.Unset()
}

// GetPurchase returns the Purchase field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetPurchase() int32 {
	if o == nil || IsNil(o.Purchase.Get()) {
		var ret int32
		return ret
	}
	return *o.Purchase.Get()
}

// GetPurchaseOk returns a tuple with the Purchase field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetPurchaseOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Purchase.Get(), o.Purchase.IsSet()
}

// HasPurchase returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasPurchase() bool {
	if o != nil && o.Purchase.IsSet() {
		return true
	}

	return false
}

// SetPurchase gets a reference to the given NullableInt32 and assigns it to the Purchase field.
func (o *PatchedWritableAssetRequest) SetPurchase(v int32) {
	o.Purchase.Set(&v)
}

// SetPurchaseNil sets the value for Purchase to be an explicit nil
func (o *PatchedWritableAssetRequest) SetPurchaseNil() {
	o.Purchase.Set(nil)
}

// UnsetPurchase ensures that no value is present for Purchase, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetPurchase() {
	o.Purchase.Unset()
}

// GetWarrantyStart returns the WarrantyStart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetWarrantyStart() string {
	if o == nil || IsNil(o.WarrantyStart.Get()) {
		var ret string
		return ret
	}
	return *o.WarrantyStart.Get()
}

// GetWarrantyStartOk returns a tuple with the WarrantyStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetWarrantyStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarrantyStart.Get(), o.WarrantyStart.IsSet()
}

// HasWarrantyStart returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasWarrantyStart() bool {
	if o != nil && o.WarrantyStart.IsSet() {
		return true
	}

	return false
}

// SetWarrantyStart gets a reference to the given NullableString and assigns it to the WarrantyStart field.
func (o *PatchedWritableAssetRequest) SetWarrantyStart(v string) {
	o.WarrantyStart.Set(&v)
}

// SetWarrantyStartNil sets the value for WarrantyStart to be an explicit nil
func (o *PatchedWritableAssetRequest) SetWarrantyStartNil() {
	o.WarrantyStart.Set(nil)
}

// UnsetWarrantyStart ensures that no value is present for WarrantyStart, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetWarrantyStart() {
	o.WarrantyStart.Unset()
}

// GetWarrantyEnd returns the WarrantyEnd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritableAssetRequest) GetWarrantyEnd() string {
	if o == nil || IsNil(o.WarrantyEnd.Get()) {
		var ret string
		return ret
	}
	return *o.WarrantyEnd.Get()
}

// GetWarrantyEndOk returns a tuple with the WarrantyEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritableAssetRequest) GetWarrantyEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.WarrantyEnd.Get(), o.WarrantyEnd.IsSet()
}

// HasWarrantyEnd returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasWarrantyEnd() bool {
	if o != nil && o.WarrantyEnd.IsSet() {
		return true
	}

	return false
}

// SetWarrantyEnd gets a reference to the given NullableString and assigns it to the WarrantyEnd field.
func (o *PatchedWritableAssetRequest) SetWarrantyEnd(v string) {
	o.WarrantyEnd.Set(&v)
}

// SetWarrantyEndNil sets the value for WarrantyEnd to be an explicit nil
func (o *PatchedWritableAssetRequest) SetWarrantyEndNil() {
	o.WarrantyEnd.Set(nil)
}

// UnsetWarrantyEnd ensures that no value is present for WarrantyEnd, not even an explicit nil
func (o *PatchedWritableAssetRequest) UnsetWarrantyEnd() {
	o.WarrantyEnd.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedWritableAssetRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableAssetRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedWritableAssetRequest) SetComments(v string) {
	o.Comments = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedWritableAssetRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableAssetRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedWritableAssetRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedWritableAssetRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritableAssetRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedWritableAssetRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedWritableAssetRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o PatchedWritableAssetRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedWritableAssetRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.AssetTag.IsSet() {
		toSerialize["asset_tag"] = o.AssetTag.Get()
	}
	if o.Serial.IsSet() {
		toSerialize["serial"] = o.Serial.Get()
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if o.DeviceType.IsSet() {
		toSerialize["device_type"] = o.DeviceType.Get()
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if o.ModuleType.IsSet() {
		toSerialize["module_type"] = o.ModuleType.Get()
	}
	if o.Module.IsSet() {
		toSerialize["module"] = o.Module.Get()
	}
	if o.InventoryitemType.IsSet() {
		toSerialize["inventoryitem_type"] = o.InventoryitemType.Get()
	}
	if o.Inventoryitem.IsSet() {
		toSerialize["inventoryitem"] = o.Inventoryitem.Get()
	}
	if o.Tenant.IsSet() {
		toSerialize["tenant"] = o.Tenant.Get()
	}
	if o.Contact.IsSet() {
		toSerialize["contact"] = o.Contact.Get()
	}
	if o.StorageLocation.IsSet() {
		toSerialize["storage_location"] = o.StorageLocation.Get()
	}
	if o.Owner.IsSet() {
		toSerialize["owner"] = o.Owner.Get()
	}
	if o.Delivery.IsSet() {
		toSerialize["delivery"] = o.Delivery.Get()
	}
	if o.Purchase.IsSet() {
		toSerialize["purchase"] = o.Purchase.Get()
	}
	if o.WarrantyStart.IsSet() {
		toSerialize["warranty_start"] = o.WarrantyStart.Get()
	}
	if o.WarrantyEnd.IsSet() {
		toSerialize["warranty_end"] = o.WarrantyEnd.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedWritableAssetRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedWritableAssetRequest := _PatchedWritableAssetRequest{}

	err = json.Unmarshal(data, &varPatchedWritableAssetRequest)

	if err != nil {
		return err
	}

	*o = PatchedWritableAssetRequest(varPatchedWritableAssetRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "asset_tag")
		delete(additionalProperties, "serial")
		delete(additionalProperties, "status")
		delete(additionalProperties, "device_type")
		delete(additionalProperties, "device")
		delete(additionalProperties, "module_type")
		delete(additionalProperties, "module")
		delete(additionalProperties, "inventoryitem_type")
		delete(additionalProperties, "inventoryitem")
		delete(additionalProperties, "tenant")
		delete(additionalProperties, "contact")
		delete(additionalProperties, "storage_location")
		delete(additionalProperties, "owner")
		delete(additionalProperties, "delivery")
		delete(additionalProperties, "purchase")
		delete(additionalProperties, "warranty_start")
		delete(additionalProperties, "warranty_end")
		delete(additionalProperties, "comments")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedWritableAssetRequest struct {
	value *PatchedWritableAssetRequest
	isSet bool
}

func (v NullablePatchedWritableAssetRequest) Get() *PatchedWritableAssetRequest {
	return v.value
}

func (v *NullablePatchedWritableAssetRequest) Set(val *PatchedWritableAssetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedWritableAssetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedWritableAssetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedWritableAssetRequest(val *PatchedWritableAssetRequest) *NullablePatchedWritableAssetRequest {
	return &NullablePatchedWritableAssetRequest{value: val, isSet: true}
}

func (v NullablePatchedWritableAssetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedWritableAssetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
