/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedPurchaseRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedPurchaseRequest{}

// NestedPurchaseRequest Represents an object related through a ForeignKey field. On write, it accepts a primary key (PK) value or a dictionary of attributes which can be used to uniquely identify the related object. This class should be subclassed to return a full representation of the related object on read.
type NestedPurchaseRequest struct {
	Name   string               `json:"name"`
	Status NestedPurchaseStatus `json:"status"`
	// Date when this purchase was made
	Date                 NullableString `json:"date,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _NestedPurchaseRequest NestedPurchaseRequest

// NewNestedPurchaseRequest instantiates a new NestedPurchaseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedPurchaseRequest(name string, status NestedPurchaseStatus) *NestedPurchaseRequest {
	this := NestedPurchaseRequest{}
	this.Name = name
	this.Status = status
	return &this
}

// NewNestedPurchaseRequestWithDefaults instantiates a new NestedPurchaseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedPurchaseRequestWithDefaults() *NestedPurchaseRequest {
	this := NestedPurchaseRequest{}
	return &this
}

// GetName returns the Name field value
func (o *NestedPurchaseRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NestedPurchaseRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NestedPurchaseRequest) SetName(v string) {
	o.Name = v
}

// GetStatus returns the Status field value
func (o *NestedPurchaseRequest) GetStatus() NestedPurchaseStatus {
	if o == nil {
		var ret NestedPurchaseStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *NestedPurchaseRequest) GetStatusOk() (*NestedPurchaseStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *NestedPurchaseRequest) SetStatus(v NestedPurchaseStatus) {
	o.Status = v
}

// GetDate returns the Date field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NestedPurchaseRequest) GetDate() string {
	if o == nil || IsNil(o.Date.Get()) {
		var ret string
		return ret
	}
	return *o.Date.Get()
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NestedPurchaseRequest) GetDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Date.Get(), o.Date.IsSet()
}

// HasDate returns a boolean if a field has been set.
func (o *NestedPurchaseRequest) HasDate() bool {
	if o != nil && o.Date.IsSet() {
		return true
	}

	return false
}

// SetDate gets a reference to the given NullableString and assigns it to the Date field.
func (o *NestedPurchaseRequest) SetDate(v string) {
	o.Date.Set(&v)
}

// SetDateNil sets the value for Date to be an explicit nil
func (o *NestedPurchaseRequest) SetDateNil() {
	o.Date.Set(nil)
}

// UnsetDate ensures that no value is present for Date, not even an explicit nil
func (o *NestedPurchaseRequest) UnsetDate() {
	o.Date.Unset()
}

func (o NestedPurchaseRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedPurchaseRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["status"] = o.Status
	if o.Date.IsSet() {
		toSerialize["date"] = o.Date.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedPurchaseRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNestedPurchaseRequest := _NestedPurchaseRequest{}

	err = json.Unmarshal(data, &varNestedPurchaseRequest)

	if err != nil {
		return err
	}

	*o = NestedPurchaseRequest(varNestedPurchaseRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "status")
		delete(additionalProperties, "date")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedPurchaseRequest struct {
	value *NestedPurchaseRequest
	isSet bool
}

func (v NullableNestedPurchaseRequest) Get() *NestedPurchaseRequest {
	return v.value
}

func (v *NullableNestedPurchaseRequest) Set(val *NestedPurchaseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedPurchaseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedPurchaseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedPurchaseRequest(val *NestedPurchaseRequest) *NullableNestedPurchaseRequest {
	return &NullableNestedPurchaseRequest{value: val, isSet: true}
}

func (v NullableNestedPurchaseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedPurchaseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
