/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BGPPeerGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BGPPeerGroupRequest{}

// BGPPeerGroupRequest Adds support for custom fields and tags.
type BGPPeerGroupRequest struct {
	Name                 string   `json:"name"`
	Description          string   `json:"description"`
	ImportPolicies       []*int32 `json:"import_policies,omitempty"`
	ExportPolicies       []*int32 `json:"export_policies,omitempty"`
	Comments             *string  `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BGPPeerGroupRequest BGPPeerGroupRequest

// NewBGPPeerGroupRequest instantiates a new BGPPeerGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBGPPeerGroupRequest(name string, description string) *BGPPeerGroupRequest {
	this := BGPPeerGroupRequest{}
	this.Name = name
	this.Description = description
	return &this
}

// NewBGPPeerGroupRequestWithDefaults instantiates a new BGPPeerGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBGPPeerGroupRequestWithDefaults() *BGPPeerGroupRequest {
	this := BGPPeerGroupRequest{}
	return &this
}

// GetName returns the Name field value
func (o *BGPPeerGroupRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BGPPeerGroupRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BGPPeerGroupRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *BGPPeerGroupRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *BGPPeerGroupRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *BGPPeerGroupRequest) SetDescription(v string) {
	o.Description = v
}

// GetImportPolicies returns the ImportPolicies field value if set, zero value otherwise.
func (o *BGPPeerGroupRequest) GetImportPolicies() []*int32 {
	if o == nil || IsNil(o.ImportPolicies) {
		var ret []*int32
		return ret
	}
	return o.ImportPolicies
}

// GetImportPoliciesOk returns a tuple with the ImportPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BGPPeerGroupRequest) GetImportPoliciesOk() ([]*int32, bool) {
	if o == nil || IsNil(o.ImportPolicies) {
		return nil, false
	}
	return o.ImportPolicies, true
}

// HasImportPolicies returns a boolean if a field has been set.
func (o *BGPPeerGroupRequest) HasImportPolicies() bool {
	if o != nil && !IsNil(o.ImportPolicies) {
		return true
	}

	return false
}

// SetImportPolicies gets a reference to the given []*int32 and assigns it to the ImportPolicies field.
func (o *BGPPeerGroupRequest) SetImportPolicies(v []*int32) {
	o.ImportPolicies = v
}

// GetExportPolicies returns the ExportPolicies field value if set, zero value otherwise.
func (o *BGPPeerGroupRequest) GetExportPolicies() []*int32 {
	if o == nil || IsNil(o.ExportPolicies) {
		var ret []*int32
		return ret
	}
	return o.ExportPolicies
}

// GetExportPoliciesOk returns a tuple with the ExportPolicies field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BGPPeerGroupRequest) GetExportPoliciesOk() ([]*int32, bool) {
	if o == nil || IsNil(o.ExportPolicies) {
		return nil, false
	}
	return o.ExportPolicies, true
}

// HasExportPolicies returns a boolean if a field has been set.
func (o *BGPPeerGroupRequest) HasExportPolicies() bool {
	if o != nil && !IsNil(o.ExportPolicies) {
		return true
	}

	return false
}

// SetExportPolicies gets a reference to the given []*int32 and assigns it to the ExportPolicies field.
func (o *BGPPeerGroupRequest) SetExportPolicies(v []*int32) {
	o.ExportPolicies = v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *BGPPeerGroupRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BGPPeerGroupRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *BGPPeerGroupRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *BGPPeerGroupRequest) SetComments(v string) {
	o.Comments = &v
}

func (o BGPPeerGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BGPPeerGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.ImportPolicies) {
		toSerialize["import_policies"] = o.ImportPolicies
	}
	if !IsNil(o.ExportPolicies) {
		toSerialize["export_policies"] = o.ExportPolicies
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BGPPeerGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBGPPeerGroupRequest := _BGPPeerGroupRequest{}

	err = json.Unmarshal(data, &varBGPPeerGroupRequest)

	if err != nil {
		return err
	}

	*o = BGPPeerGroupRequest(varBGPPeerGroupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "import_policies")
		delete(additionalProperties, "export_policies")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBGPPeerGroupRequest struct {
	value *BGPPeerGroupRequest
	isSet bool
}

func (v NullableBGPPeerGroupRequest) Get() *BGPPeerGroupRequest {
	return v.value
}

func (v *NullableBGPPeerGroupRequest) Set(val *BGPPeerGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBGPPeerGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBGPPeerGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBGPPeerGroupRequest(val *BGPPeerGroupRequest) *NullableBGPPeerGroupRequest {
	return &NullableBGPPeerGroupRequest{value: val, isSet: true}
}

func (v NullableBGPPeerGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBGPPeerGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
