/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedWritablePrefixListRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedWritablePrefixListRuleRequest{}

// PatchedWritablePrefixListRuleRequest Adds support for custom fields and tags.
type PatchedWritablePrefixListRuleRequest struct {
	Tags                 []NestedTagRequest       `json:"tags,omitempty"`
	CustomFields         map[string]interface{}   `json:"custom_fields,omitempty"`
	PrefixList           *int32                   `json:"prefix_list,omitempty"`
	Index                *int32                   `json:"index,omitempty"`
	Action               *CommunityListRuleAction `json:"action,omitempty"`
	PrefixCustom         NullableString           `json:"prefix_custom,omitempty"`
	Ge                   NullableInt32            `json:"ge,omitempty"`
	Le                   NullableInt32            `json:"le,omitempty"`
	Prefix               NullableInt32            `json:"prefix,omitempty"`
	Comments             *string                  `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedWritablePrefixListRuleRequest PatchedWritablePrefixListRuleRequest

// NewPatchedWritablePrefixListRuleRequest instantiates a new PatchedWritablePrefixListRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedWritablePrefixListRuleRequest() *PatchedWritablePrefixListRuleRequest {
	this := PatchedWritablePrefixListRuleRequest{}
	return &this
}

// NewPatchedWritablePrefixListRuleRequestWithDefaults instantiates a new PatchedWritablePrefixListRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedWritablePrefixListRuleRequestWithDefaults() *PatchedWritablePrefixListRuleRequest {
	this := PatchedWritablePrefixListRuleRequest{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedWritablePrefixListRuleRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedWritablePrefixListRuleRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetPrefixList returns the PrefixList field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetPrefixList() int32 {
	if o == nil || IsNil(o.PrefixList) {
		var ret int32
		return ret
	}
	return *o.PrefixList
}

// GetPrefixListOk returns a tuple with the PrefixList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetPrefixListOk() (*int32, bool) {
	if o == nil || IsNil(o.PrefixList) {
		return nil, false
	}
	return o.PrefixList, true
}

// HasPrefixList returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasPrefixList() bool {
	if o != nil && !IsNil(o.PrefixList) {
		return true
	}

	return false
}

// SetPrefixList gets a reference to the given int32 and assigns it to the PrefixList field.
func (o *PatchedWritablePrefixListRuleRequest) SetPrefixList(v int32) {
	o.PrefixList = &v
}

// GetIndex returns the Index field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetIndex() int32 {
	if o == nil || IsNil(o.Index) {
		var ret int32
		return ret
	}
	return *o.Index
}

// GetIndexOk returns a tuple with the Index field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetIndexOk() (*int32, bool) {
	if o == nil || IsNil(o.Index) {
		return nil, false
	}
	return o.Index, true
}

// HasIndex returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasIndex() bool {
	if o != nil && !IsNil(o.Index) {
		return true
	}

	return false
}

// SetIndex gets a reference to the given int32 and assigns it to the Index field.
func (o *PatchedWritablePrefixListRuleRequest) SetIndex(v int32) {
	o.Index = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetAction() CommunityListRuleAction {
	if o == nil || IsNil(o.Action) {
		var ret CommunityListRuleAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetActionOk() (*CommunityListRuleAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given CommunityListRuleAction and assigns it to the Action field.
func (o *PatchedWritablePrefixListRuleRequest) SetAction(v CommunityListRuleAction) {
	o.Action = &v
}

// GetPrefixCustom returns the PrefixCustom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritablePrefixListRuleRequest) GetPrefixCustom() string {
	if o == nil || IsNil(o.PrefixCustom.Get()) {
		var ret string
		return ret
	}
	return *o.PrefixCustom.Get()
}

// GetPrefixCustomOk returns a tuple with the PrefixCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritablePrefixListRuleRequest) GetPrefixCustomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrefixCustom.Get(), o.PrefixCustom.IsSet()
}

// HasPrefixCustom returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasPrefixCustom() bool {
	if o != nil && o.PrefixCustom.IsSet() {
		return true
	}

	return false
}

// SetPrefixCustom gets a reference to the given NullableString and assigns it to the PrefixCustom field.
func (o *PatchedWritablePrefixListRuleRequest) SetPrefixCustom(v string) {
	o.PrefixCustom.Set(&v)
}

// SetPrefixCustomNil sets the value for PrefixCustom to be an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) SetPrefixCustomNil() {
	o.PrefixCustom.Set(nil)
}

// UnsetPrefixCustom ensures that no value is present for PrefixCustom, not even an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) UnsetPrefixCustom() {
	o.PrefixCustom.Unset()
}

// GetGe returns the Ge field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritablePrefixListRuleRequest) GetGe() int32 {
	if o == nil || IsNil(o.Ge.Get()) {
		var ret int32
		return ret
	}
	return *o.Ge.Get()
}

// GetGeOk returns a tuple with the Ge field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritablePrefixListRuleRequest) GetGeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ge.Get(), o.Ge.IsSet()
}

// HasGe returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasGe() bool {
	if o != nil && o.Ge.IsSet() {
		return true
	}

	return false
}

// SetGe gets a reference to the given NullableInt32 and assigns it to the Ge field.
func (o *PatchedWritablePrefixListRuleRequest) SetGe(v int32) {
	o.Ge.Set(&v)
}

// SetGeNil sets the value for Ge to be an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) SetGeNil() {
	o.Ge.Set(nil)
}

// UnsetGe ensures that no value is present for Ge, not even an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) UnsetGe() {
	o.Ge.Unset()
}

// GetLe returns the Le field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritablePrefixListRuleRequest) GetLe() int32 {
	if o == nil || IsNil(o.Le.Get()) {
		var ret int32
		return ret
	}
	return *o.Le.Get()
}

// GetLeOk returns a tuple with the Le field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritablePrefixListRuleRequest) GetLeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Le.Get(), o.Le.IsSet()
}

// HasLe returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasLe() bool {
	if o != nil && o.Le.IsSet() {
		return true
	}

	return false
}

// SetLe gets a reference to the given NullableInt32 and assigns it to the Le field.
func (o *PatchedWritablePrefixListRuleRequest) SetLe(v int32) {
	o.Le.Set(&v)
}

// SetLeNil sets the value for Le to be an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) SetLeNil() {
	o.Le.Set(nil)
}

// UnsetLe ensures that no value is present for Le, not even an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) UnsetLe() {
	o.Le.Unset()
}

// GetPrefix returns the Prefix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedWritablePrefixListRuleRequest) GetPrefix() int32 {
	if o == nil || IsNil(o.Prefix.Get()) {
		var ret int32
		return ret
	}
	return *o.Prefix.Get()
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedWritablePrefixListRuleRequest) GetPrefixOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefix.Get(), o.Prefix.IsSet()
}

// HasPrefix returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasPrefix() bool {
	if o != nil && o.Prefix.IsSet() {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given NullableInt32 and assigns it to the Prefix field.
func (o *PatchedWritablePrefixListRuleRequest) SetPrefix(v int32) {
	o.Prefix.Set(&v)
}

// SetPrefixNil sets the value for Prefix to be an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) SetPrefixNil() {
	o.Prefix.Set(nil)
}

// UnsetPrefix ensures that no value is present for Prefix, not even an explicit nil
func (o *PatchedWritablePrefixListRuleRequest) UnsetPrefix() {
	o.Prefix.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedWritablePrefixListRuleRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedWritablePrefixListRuleRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedWritablePrefixListRuleRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedWritablePrefixListRuleRequest) SetComments(v string) {
	o.Comments = &v
}

func (o PatchedWritablePrefixListRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedWritablePrefixListRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.PrefixList) {
		toSerialize["prefix_list"] = o.PrefixList
	}
	if !IsNil(o.Index) {
		toSerialize["index"] = o.Index
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if o.PrefixCustom.IsSet() {
		toSerialize["prefix_custom"] = o.PrefixCustom.Get()
	}
	if o.Ge.IsSet() {
		toSerialize["ge"] = o.Ge.Get()
	}
	if o.Le.IsSet() {
		toSerialize["le"] = o.Le.Get()
	}
	if o.Prefix.IsSet() {
		toSerialize["prefix"] = o.Prefix.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedWritablePrefixListRuleRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedWritablePrefixListRuleRequest := _PatchedWritablePrefixListRuleRequest{}

	err = json.Unmarshal(data, &varPatchedWritablePrefixListRuleRequest)

	if err != nil {
		return err
	}

	*o = PatchedWritablePrefixListRuleRequest(varPatchedWritablePrefixListRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "prefix_list")
		delete(additionalProperties, "index")
		delete(additionalProperties, "action")
		delete(additionalProperties, "prefix_custom")
		delete(additionalProperties, "ge")
		delete(additionalProperties, "le")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedWritablePrefixListRuleRequest struct {
	value *PatchedWritablePrefixListRuleRequest
	isSet bool
}

func (v NullablePatchedWritablePrefixListRuleRequest) Get() *PatchedWritablePrefixListRuleRequest {
	return v.value
}

func (v *NullablePatchedWritablePrefixListRuleRequest) Set(val *PatchedWritablePrefixListRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedWritablePrefixListRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedWritablePrefixListRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedWritablePrefixListRuleRequest(val *PatchedWritablePrefixListRuleRequest) *NullablePatchedWritablePrefixListRuleRequest {
	return &NullablePatchedWritablePrefixListRuleRequest{value: val, isSet: true}
}

func (v NullablePatchedWritablePrefixListRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedWritablePrefixListRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
