/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the SiteStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SiteStatus{}

// SiteStatus struct for SiteStatus
type SiteStatus struct {
	Value                *PatchedWritableSiteRequestStatus `json:"value,omitempty"`
	Label                *SiteStatusLabel                  `json:"label,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SiteStatus SiteStatus

// NewSiteStatus instantiates a new SiteStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSiteStatus() *SiteStatus {
	this := SiteStatus{}
	return &this
}

// NewSiteStatusWithDefaults instantiates a new SiteStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSiteStatusWithDefaults() *SiteStatus {
	this := SiteStatus{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *SiteStatus) GetValue() PatchedWritableSiteRequestStatus {
	if o == nil || IsNil(o.Value) {
		var ret PatchedWritableSiteRequestStatus
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteStatus) GetValueOk() (*PatchedWritableSiteRequestStatus, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *SiteStatus) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given PatchedWritableSiteRequestStatus and assigns it to the Value field.
func (o *SiteStatus) SetValue(v PatchedWritableSiteRequestStatus) {
	o.Value = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *SiteStatus) GetLabel() SiteStatusLabel {
	if o == nil || IsNil(o.Label) {
		var ret SiteStatusLabel
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SiteStatus) GetLabelOk() (*SiteStatusLabel, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *SiteStatus) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given SiteStatusLabel and assigns it to the Label field.
func (o *SiteStatus) SetLabel(v SiteStatusLabel) {
	o.Label = &v
}

func (o SiteStatus) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SiteStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SiteStatus) UnmarshalJSON(data []byte) (err error) {
	varSiteStatus := _SiteStatus{}

	err = json.Unmarshal(data, &varSiteStatus)

	if err != nil {
		return err
	}

	*o = SiteStatus(varSiteStatus)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "value")
		delete(additionalProperties, "label")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSiteStatus struct {
	value *SiteStatus
	isSet bool
}

func (v NullableSiteStatus) Get() *SiteStatus {
	return v.value
}

func (v *NullableSiteStatus) Set(val *SiteStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSiteStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSiteStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSiteStatus(val *SiteStatus) *NullableSiteStatus {
	return &NullableSiteStatus{value: val, isSet: true}
}

func (v NullableSiteStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSiteStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
