/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
)

// checks if the PatchedCommunityListRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedCommunityListRuleRequest{}

// PatchedCommunityListRuleRequest Adds support for custom fields and tags.
type PatchedCommunityListRuleRequest struct {
	Tags                 []NestedTagRequest            `json:"tags,omitempty"`
	CustomFields         map[string]interface{}        `json:"custom_fields,omitempty"`
	Description          *string                       `json:"description,omitempty"`
	CommunityList        *BriefCommunityListRequest    `json:"community_list,omitempty"`
	Action               *CommunityListRuleAction      `json:"action,omitempty"`
	Community            NullableBriefCommunityRequest `json:"community,omitempty"`
	Comments             *string                       `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedCommunityListRuleRequest PatchedCommunityListRuleRequest

// NewPatchedCommunityListRuleRequest instantiates a new PatchedCommunityListRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedCommunityListRuleRequest() *PatchedCommunityListRuleRequest {
	this := PatchedCommunityListRuleRequest{}
	return &this
}

// NewPatchedCommunityListRuleRequestWithDefaults instantiates a new PatchedCommunityListRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedCommunityListRuleRequestWithDefaults() *PatchedCommunityListRuleRequest {
	this := PatchedCommunityListRuleRequest{}
	return &this
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PatchedCommunityListRuleRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedCommunityListRuleRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PatchedCommunityListRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCommunityList returns the CommunityList field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetCommunityList() BriefCommunityListRequest {
	if o == nil || IsNil(o.CommunityList) {
		var ret BriefCommunityListRequest
		return ret
	}
	return *o.CommunityList
}

// GetCommunityListOk returns a tuple with the CommunityList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetCommunityListOk() (*BriefCommunityListRequest, bool) {
	if o == nil || IsNil(o.CommunityList) {
		return nil, false
	}
	return o.CommunityList, true
}

// HasCommunityList returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasCommunityList() bool {
	if o != nil && !IsNil(o.CommunityList) {
		return true
	}

	return false
}

// SetCommunityList gets a reference to the given BriefCommunityListRequest and assigns it to the CommunityList field.
func (o *PatchedCommunityListRuleRequest) SetCommunityList(v BriefCommunityListRequest) {
	o.CommunityList = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetAction() CommunityListRuleAction {
	if o == nil || IsNil(o.Action) {
		var ret CommunityListRuleAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetActionOk() (*CommunityListRuleAction, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given CommunityListRuleAction and assigns it to the Action field.
func (o *PatchedCommunityListRuleRequest) SetAction(v CommunityListRuleAction) {
	o.Action = &v
}

// GetCommunity returns the Community field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedCommunityListRuleRequest) GetCommunity() BriefCommunityRequest {
	if o == nil || IsNil(o.Community.Get()) {
		var ret BriefCommunityRequest
		return ret
	}
	return *o.Community.Get()
}

// GetCommunityOk returns a tuple with the Community field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedCommunityListRuleRequest) GetCommunityOk() (*BriefCommunityRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Community.Get(), o.Community.IsSet()
}

// HasCommunity returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasCommunity() bool {
	if o != nil && o.Community.IsSet() {
		return true
	}

	return false
}

// SetCommunity gets a reference to the given NullableBriefCommunityRequest and assigns it to the Community field.
func (o *PatchedCommunityListRuleRequest) SetCommunity(v BriefCommunityRequest) {
	o.Community.Set(&v)
}

// SetCommunityNil sets the value for Community to be an explicit nil
func (o *PatchedCommunityListRuleRequest) SetCommunityNil() {
	o.Community.Set(nil)
}

// UnsetCommunity ensures that no value is present for Community, not even an explicit nil
func (o *PatchedCommunityListRuleRequest) UnsetCommunity() {
	o.Community.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PatchedCommunityListRuleRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedCommunityListRuleRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PatchedCommunityListRuleRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PatchedCommunityListRuleRequest) SetComments(v string) {
	o.Comments = &v
}

func (o PatchedCommunityListRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedCommunityListRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.CommunityList) {
		toSerialize["community_list"] = o.CommunityList
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if o.Community.IsSet() {
		toSerialize["community"] = o.Community.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedCommunityListRuleRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedCommunityListRuleRequest := _PatchedCommunityListRuleRequest{}

	err = json.Unmarshal(data, &varPatchedCommunityListRuleRequest)

	if err != nil {
		return err
	}

	*o = PatchedCommunityListRuleRequest(varPatchedCommunityListRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "description")
		delete(additionalProperties, "community_list")
		delete(additionalProperties, "action")
		delete(additionalProperties, "community")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedCommunityListRuleRequest struct {
	value *PatchedCommunityListRuleRequest
	isSet bool
}

func (v NullablePatchedCommunityListRuleRequest) Get() *PatchedCommunityListRuleRequest {
	return v.value
}

func (v *NullablePatchedCommunityListRuleRequest) Set(val *PatchedCommunityListRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedCommunityListRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedCommunityListRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedCommunityListRuleRequest(val *PatchedCommunityListRuleRequest) *NullablePatchedCommunityListRuleRequest {
	return &NullablePatchedCommunityListRuleRequest{value: val, isSet: true}
}

func (v NullablePatchedCommunityListRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedCommunityListRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
