/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the PrefixListRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PrefixListRuleRequest{}

// PrefixListRuleRequest Adds support for custom fields and tags.
type PrefixListRuleRequest struct {
	Description          *string                    `json:"description,omitempty"`
	Tags                 []NestedTagRequest         `json:"tags,omitempty"`
	CustomFields         map[string]interface{}     `json:"custom_fields,omitempty"`
	PrefixList           BriefPrefixListRequest     `json:"prefix_list"`
	Index                int32                      `json:"index"`
	Action               CommunityListRuleAction    `json:"action"`
	PrefixCustom         NullableString             `json:"prefix_custom,omitempty"`
	Ge                   NullableInt32              `json:"ge,omitempty"`
	Le                   NullableInt32              `json:"le,omitempty"`
	Prefix               NullableBriefPrefixRequest `json:"prefix,omitempty"`
	Comments             *string                    `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PrefixListRuleRequest PrefixListRuleRequest

// NewPrefixListRuleRequest instantiates a new PrefixListRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPrefixListRuleRequest(prefixList BriefPrefixListRequest, index int32, action CommunityListRuleAction) *PrefixListRuleRequest {
	this := PrefixListRuleRequest{}
	this.PrefixList = prefixList
	this.Index = index
	this.Action = action
	return &this
}

// NewPrefixListRuleRequestWithDefaults instantiates a new PrefixListRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPrefixListRuleRequestWithDefaults() *PrefixListRuleRequest {
	this := PrefixListRuleRequest{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *PrefixListRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *PrefixListRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PrefixListRuleRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *PrefixListRuleRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PrefixListRuleRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PrefixListRuleRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetPrefixList returns the PrefixList field value
func (o *PrefixListRuleRequest) GetPrefixList() BriefPrefixListRequest {
	if o == nil {
		var ret BriefPrefixListRequest
		return ret
	}

	return o.PrefixList
}

// GetPrefixListOk returns a tuple with the PrefixList field value
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetPrefixListOk() (*BriefPrefixListRequest, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrefixList, true
}

// SetPrefixList sets field value
func (o *PrefixListRuleRequest) SetPrefixList(v BriefPrefixListRequest) {
	o.PrefixList = v
}

// GetIndex returns the Index field value
func (o *PrefixListRuleRequest) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *PrefixListRuleRequest) SetIndex(v int32) {
	o.Index = v
}

// GetAction returns the Action field value
func (o *PrefixListRuleRequest) GetAction() CommunityListRuleAction {
	if o == nil {
		var ret CommunityListRuleAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetActionOk() (*CommunityListRuleAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *PrefixListRuleRequest) SetAction(v CommunityListRuleAction) {
	o.Action = v
}

// GetPrefixCustom returns the PrefixCustom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrefixListRuleRequest) GetPrefixCustom() string {
	if o == nil || IsNil(o.PrefixCustom.Get()) {
		var ret string
		return ret
	}
	return *o.PrefixCustom.Get()
}

// GetPrefixCustomOk returns a tuple with the PrefixCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrefixListRuleRequest) GetPrefixCustomOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PrefixCustom.Get(), o.PrefixCustom.IsSet()
}

// HasPrefixCustom returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasPrefixCustom() bool {
	if o != nil && o.PrefixCustom.IsSet() {
		return true
	}

	return false
}

// SetPrefixCustom gets a reference to the given NullableString and assigns it to the PrefixCustom field.
func (o *PrefixListRuleRequest) SetPrefixCustom(v string) {
	o.PrefixCustom.Set(&v)
}

// SetPrefixCustomNil sets the value for PrefixCustom to be an explicit nil
func (o *PrefixListRuleRequest) SetPrefixCustomNil() {
	o.PrefixCustom.Set(nil)
}

// UnsetPrefixCustom ensures that no value is present for PrefixCustom, not even an explicit nil
func (o *PrefixListRuleRequest) UnsetPrefixCustom() {
	o.PrefixCustom.Unset()
}

// GetGe returns the Ge field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrefixListRuleRequest) GetGe() int32 {
	if o == nil || IsNil(o.Ge.Get()) {
		var ret int32
		return ret
	}
	return *o.Ge.Get()
}

// GetGeOk returns a tuple with the Ge field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrefixListRuleRequest) GetGeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ge.Get(), o.Ge.IsSet()
}

// HasGe returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasGe() bool {
	if o != nil && o.Ge.IsSet() {
		return true
	}

	return false
}

// SetGe gets a reference to the given NullableInt32 and assigns it to the Ge field.
func (o *PrefixListRuleRequest) SetGe(v int32) {
	o.Ge.Set(&v)
}

// SetGeNil sets the value for Ge to be an explicit nil
func (o *PrefixListRuleRequest) SetGeNil() {
	o.Ge.Set(nil)
}

// UnsetGe ensures that no value is present for Ge, not even an explicit nil
func (o *PrefixListRuleRequest) UnsetGe() {
	o.Ge.Unset()
}

// GetLe returns the Le field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrefixListRuleRequest) GetLe() int32 {
	if o == nil || IsNil(o.Le.Get()) {
		var ret int32
		return ret
	}
	return *o.Le.Get()
}

// GetLeOk returns a tuple with the Le field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrefixListRuleRequest) GetLeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.Le.Get(), o.Le.IsSet()
}

// HasLe returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasLe() bool {
	if o != nil && o.Le.IsSet() {
		return true
	}

	return false
}

// SetLe gets a reference to the given NullableInt32 and assigns it to the Le field.
func (o *PrefixListRuleRequest) SetLe(v int32) {
	o.Le.Set(&v)
}

// SetLeNil sets the value for Le to be an explicit nil
func (o *PrefixListRuleRequest) SetLeNil() {
	o.Le.Set(nil)
}

// UnsetLe ensures that no value is present for Le, not even an explicit nil
func (o *PrefixListRuleRequest) UnsetLe() {
	o.Le.Unset()
}

// GetPrefix returns the Prefix field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PrefixListRuleRequest) GetPrefix() BriefPrefixRequest {
	if o == nil || IsNil(o.Prefix.Get()) {
		var ret BriefPrefixRequest
		return ret
	}
	return *o.Prefix.Get()
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PrefixListRuleRequest) GetPrefixOk() (*BriefPrefixRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Prefix.Get(), o.Prefix.IsSet()
}

// HasPrefix returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasPrefix() bool {
	if o != nil && o.Prefix.IsSet() {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given NullableBriefPrefixRequest and assigns it to the Prefix field.
func (o *PrefixListRuleRequest) SetPrefix(v BriefPrefixRequest) {
	o.Prefix.Set(&v)
}

// SetPrefixNil sets the value for Prefix to be an explicit nil
func (o *PrefixListRuleRequest) SetPrefixNil() {
	o.Prefix.Set(nil)
}

// UnsetPrefix ensures that no value is present for Prefix, not even an explicit nil
func (o *PrefixListRuleRequest) UnsetPrefix() {
	o.Prefix.Unset()
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *PrefixListRuleRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PrefixListRuleRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *PrefixListRuleRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *PrefixListRuleRequest) SetComments(v string) {
	o.Comments = &v
}

func (o PrefixListRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PrefixListRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	toSerialize["prefix_list"] = o.PrefixList
	toSerialize["index"] = o.Index
	toSerialize["action"] = o.Action
	if o.PrefixCustom.IsSet() {
		toSerialize["prefix_custom"] = o.PrefixCustom.Get()
	}
	if o.Ge.IsSet() {
		toSerialize["ge"] = o.Ge.Get()
	}
	if o.Le.IsSet() {
		toSerialize["le"] = o.Le.Get()
	}
	if o.Prefix.IsSet() {
		toSerialize["prefix"] = o.Prefix.Get()
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PrefixListRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"prefix_list",
		"index",
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPrefixListRuleRequest := _PrefixListRuleRequest{}

	err = json.Unmarshal(data, &varPrefixListRuleRequest)

	if err != nil {
		return err
	}

	*o = PrefixListRuleRequest(varPrefixListRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "prefix_list")
		delete(additionalProperties, "index")
		delete(additionalProperties, "action")
		delete(additionalProperties, "prefix_custom")
		delete(additionalProperties, "ge")
		delete(additionalProperties, "le")
		delete(additionalProperties, "prefix")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePrefixListRuleRequest struct {
	value *PrefixListRuleRequest
	isSet bool
}

func (v NullablePrefixListRuleRequest) Get() *PrefixListRuleRequest {
	return v.value
}

func (v *NullablePrefixListRuleRequest) Set(val *PrefixListRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePrefixListRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePrefixListRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePrefixListRuleRequest(val *PrefixListRuleRequest) *NullablePrefixListRuleRequest {
	return &NullablePrefixListRuleRequest{value: val, isSet: true}
}

func (v NullablePrefixListRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePrefixListRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
