/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefCommunityListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefCommunityListRequest{}

// BriefCommunityListRequest Adds support for custom fields and tags.
type BriefCommunityListRequest struct {
	Name                 string `json:"name"`
	Description          string `json:"description"`
	AdditionalProperties map[string]interface{}
}

type _BriefCommunityListRequest BriefCommunityListRequest

// NewBriefCommunityListRequest instantiates a new BriefCommunityListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefCommunityListRequest(name string, description string) *BriefCommunityListRequest {
	this := BriefCommunityListRequest{}
	this.Name = name
	this.Description = description
	return &this
}

// NewBriefCommunityListRequestWithDefaults instantiates a new BriefCommunityListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefCommunityListRequestWithDefaults() *BriefCommunityListRequest {
	this := BriefCommunityListRequest{}
	return &this
}

// GetName returns the Name field value
func (o *BriefCommunityListRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BriefCommunityListRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BriefCommunityListRequest) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *BriefCommunityListRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *BriefCommunityListRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *BriefCommunityListRequest) SetDescription(v string) {
	o.Description = v
}

func (o BriefCommunityListRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefCommunityListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefCommunityListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBriefCommunityListRequest := _BriefCommunityListRequest{}

	err = json.Unmarshal(data, &varBriefCommunityListRequest)

	if err != nil {
		return err
	}

	*o = BriefCommunityListRequest(varBriefCommunityListRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefCommunityListRequest struct {
	value *BriefCommunityListRequest
	isSet bool
}

func (v NullableBriefCommunityListRequest) Get() *BriefCommunityListRequest {
	return v.value
}

func (v *NullableBriefCommunityListRequest) Set(val *BriefCommunityListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefCommunityListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefCommunityListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefCommunityListRequest(val *BriefCommunityListRequest) *NullableBriefCommunityListRequest {
	return &NullableBriefCommunityListRequest{value: val, isSet: true}
}

func (v NullableBriefCommunityListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefCommunityListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
