/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 4.0.11 (4.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the BriefASNRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BriefASNRequest{}

// BriefASNRequest Adds support for custom fields and tags.
type BriefASNRequest struct {
	// 16- or 32-bit autonomous system number
	Asn                  int64   `json:"asn"`
	Description          *string `json:"description,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BriefASNRequest BriefASNRequest

// NewBriefASNRequest instantiates a new BriefASNRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBriefASNRequest(asn int64) *BriefASNRequest {
	this := BriefASNRequest{}
	this.Asn = asn
	return &this
}

// NewBriefASNRequestWithDefaults instantiates a new BriefASNRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBriefASNRequestWithDefaults() *BriefASNRequest {
	this := BriefASNRequest{}
	return &this
}

// GetAsn returns the Asn field value
func (o *BriefASNRequest) GetAsn() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Asn
}

// GetAsnOk returns a tuple with the Asn field value
// and a boolean to check if the value has been set.
func (o *BriefASNRequest) GetAsnOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asn, true
}

// SetAsn sets field value
func (o *BriefASNRequest) SetAsn(v int64) {
	o.Asn = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *BriefASNRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BriefASNRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *BriefASNRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *BriefASNRequest) SetDescription(v string) {
	o.Description = &v
}

func (o BriefASNRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BriefASNRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["asn"] = o.Asn
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BriefASNRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"asn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBriefASNRequest := _BriefASNRequest{}

	err = json.Unmarshal(data, &varBriefASNRequest)

	if err != nil {
		return err
	}

	*o = BriefASNRequest(varBriefASNRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "asn")
		delete(additionalProperties, "description")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBriefASNRequest struct {
	value *BriefASNRequest
	isSet bool
}

func (v NullableBriefASNRequest) Get() *BriefASNRequest {
	return v.value
}

func (v *NullableBriefASNRequest) Set(val *BriefASNRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBriefASNRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBriefASNRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBriefASNRequest(val *BriefASNRequest) *NullableBriefASNRequest {
	return &NullableBriefASNRequest{value: val, isSet: true}
}

func (v NullableBriefASNRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBriefASNRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
