/*
NetBox REST API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.7.8 (3.7)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package netbox

import (
	"encoding/json"
	"fmt"
)

// checks if the WritableRoutingPolicyRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WritableRoutingPolicyRuleRequest{}

// WritableRoutingPolicyRuleRequest Adds support for custom fields and tags.
type WritableRoutingPolicyRuleRequest struct {
	Index                int32                   `json:"index"`
	Action               CommunityListRuleAction `json:"action"`
	MatchIpAddress       []*int32                `json:"match_ip_address,omitempty"`
	RoutingPolicy        int32                   `json:"routing_policy"`
	MatchCommunity       []*int32                `json:"match_community,omitempty"`
	MatchCustom          interface{}             `json:"match_custom,omitempty"`
	SetActions           interface{}             `json:"set_actions,omitempty"`
	MatchIpv6Address     []int32                 `json:"match_ipv6_address,omitempty"`
	Description          *string                 `json:"description,omitempty"`
	Tags                 []NestedTagRequest      `json:"tags,omitempty"`
	CustomFields         map[string]interface{}  `json:"custom_fields,omitempty"`
	Comments             *string                 `json:"comments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WritableRoutingPolicyRuleRequest WritableRoutingPolicyRuleRequest

// NewWritableRoutingPolicyRuleRequest instantiates a new WritableRoutingPolicyRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWritableRoutingPolicyRuleRequest(index int32, action CommunityListRuleAction, routingPolicy int32) *WritableRoutingPolicyRuleRequest {
	this := WritableRoutingPolicyRuleRequest{}
	this.Index = index
	this.Action = action
	this.RoutingPolicy = routingPolicy
	return &this
}

// NewWritableRoutingPolicyRuleRequestWithDefaults instantiates a new WritableRoutingPolicyRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWritableRoutingPolicyRuleRequestWithDefaults() *WritableRoutingPolicyRuleRequest {
	this := WritableRoutingPolicyRuleRequest{}
	return &this
}

// GetIndex returns the Index field value
func (o *WritableRoutingPolicyRuleRequest) GetIndex() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Index
}

// GetIndexOk returns a tuple with the Index field value
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Index, true
}

// SetIndex sets field value
func (o *WritableRoutingPolicyRuleRequest) SetIndex(v int32) {
	o.Index = v
}

// GetAction returns the Action field value
func (o *WritableRoutingPolicyRuleRequest) GetAction() CommunityListRuleAction {
	if o == nil {
		var ret CommunityListRuleAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetActionOk() (*CommunityListRuleAction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *WritableRoutingPolicyRuleRequest) SetAction(v CommunityListRuleAction) {
	o.Action = v
}

// GetMatchIpAddress returns the MatchIpAddress field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetMatchIpAddress() []*int32 {
	if o == nil || IsNil(o.MatchIpAddress) {
		var ret []*int32
		return ret
	}
	return o.MatchIpAddress
}

// GetMatchIpAddressOk returns a tuple with the MatchIpAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetMatchIpAddressOk() ([]*int32, bool) {
	if o == nil || IsNil(o.MatchIpAddress) {
		return nil, false
	}
	return o.MatchIpAddress, true
}

// HasMatchIpAddress returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasMatchIpAddress() bool {
	if o != nil && !IsNil(o.MatchIpAddress) {
		return true
	}

	return false
}

// SetMatchIpAddress gets a reference to the given []*int32 and assigns it to the MatchIpAddress field.
func (o *WritableRoutingPolicyRuleRequest) SetMatchIpAddress(v []*int32) {
	o.MatchIpAddress = v
}

// GetRoutingPolicy returns the RoutingPolicy field value
func (o *WritableRoutingPolicyRuleRequest) GetRoutingPolicy() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RoutingPolicy
}

// GetRoutingPolicyOk returns a tuple with the RoutingPolicy field value
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetRoutingPolicyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoutingPolicy, true
}

// SetRoutingPolicy sets field value
func (o *WritableRoutingPolicyRuleRequest) SetRoutingPolicy(v int32) {
	o.RoutingPolicy = v
}

// GetMatchCommunity returns the MatchCommunity field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetMatchCommunity() []*int32 {
	if o == nil || IsNil(o.MatchCommunity) {
		var ret []*int32
		return ret
	}
	return o.MatchCommunity
}

// GetMatchCommunityOk returns a tuple with the MatchCommunity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetMatchCommunityOk() ([]*int32, bool) {
	if o == nil || IsNil(o.MatchCommunity) {
		return nil, false
	}
	return o.MatchCommunity, true
}

// HasMatchCommunity returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasMatchCommunity() bool {
	if o != nil && !IsNil(o.MatchCommunity) {
		return true
	}

	return false
}

// SetMatchCommunity gets a reference to the given []*int32 and assigns it to the MatchCommunity field.
func (o *WritableRoutingPolicyRuleRequest) SetMatchCommunity(v []*int32) {
	o.MatchCommunity = v
}

// GetMatchCustom returns the MatchCustom field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WritableRoutingPolicyRuleRequest) GetMatchCustom() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.MatchCustom
}

// GetMatchCustomOk returns a tuple with the MatchCustom field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WritableRoutingPolicyRuleRequest) GetMatchCustomOk() (*interface{}, bool) {
	if o == nil || IsNil(o.MatchCustom) {
		return nil, false
	}
	return &o.MatchCustom, true
}

// HasMatchCustom returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasMatchCustom() bool {
	if o != nil && !IsNil(o.MatchCustom) {
		return true
	}

	return false
}

// SetMatchCustom gets a reference to the given interface{} and assigns it to the MatchCustom field.
func (o *WritableRoutingPolicyRuleRequest) SetMatchCustom(v interface{}) {
	o.MatchCustom = v
}

// GetSetActions returns the SetActions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WritableRoutingPolicyRuleRequest) GetSetActions() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.SetActions
}

// GetSetActionsOk returns a tuple with the SetActions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WritableRoutingPolicyRuleRequest) GetSetActionsOk() (*interface{}, bool) {
	if o == nil || IsNil(o.SetActions) {
		return nil, false
	}
	return &o.SetActions, true
}

// HasSetActions returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasSetActions() bool {
	if o != nil && !IsNil(o.SetActions) {
		return true
	}

	return false
}

// SetSetActions gets a reference to the given interface{} and assigns it to the SetActions field.
func (o *WritableRoutingPolicyRuleRequest) SetSetActions(v interface{}) {
	o.SetActions = v
}

// GetMatchIpv6Address returns the MatchIpv6Address field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetMatchIpv6Address() []int32 {
	if o == nil || IsNil(o.MatchIpv6Address) {
		var ret []int32
		return ret
	}
	return o.MatchIpv6Address
}

// GetMatchIpv6AddressOk returns a tuple with the MatchIpv6Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetMatchIpv6AddressOk() ([]int32, bool) {
	if o == nil || IsNil(o.MatchIpv6Address) {
		return nil, false
	}
	return o.MatchIpv6Address, true
}

// HasMatchIpv6Address returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasMatchIpv6Address() bool {
	if o != nil && !IsNil(o.MatchIpv6Address) {
		return true
	}

	return false
}

// SetMatchIpv6Address gets a reference to the given []int32 and assigns it to the MatchIpv6Address field.
func (o *WritableRoutingPolicyRuleRequest) SetMatchIpv6Address(v []int32) {
	o.MatchIpv6Address = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *WritableRoutingPolicyRuleRequest) SetDescription(v string) {
	o.Description = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetTags() []NestedTagRequest {
	if o == nil || IsNil(o.Tags) {
		var ret []NestedTagRequest
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetTagsOk() ([]NestedTagRequest, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []NestedTagRequest and assigns it to the Tags field.
func (o *WritableRoutingPolicyRuleRequest) SetTags(v []NestedTagRequest) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *WritableRoutingPolicyRuleRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetComments returns the Comments field value if set, zero value otherwise.
func (o *WritableRoutingPolicyRuleRequest) GetComments() string {
	if o == nil || IsNil(o.Comments) {
		var ret string
		return ret
	}
	return *o.Comments
}

// GetCommentsOk returns a tuple with the Comments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WritableRoutingPolicyRuleRequest) GetCommentsOk() (*string, bool) {
	if o == nil || IsNil(o.Comments) {
		return nil, false
	}
	return o.Comments, true
}

// HasComments returns a boolean if a field has been set.
func (o *WritableRoutingPolicyRuleRequest) HasComments() bool {
	if o != nil && !IsNil(o.Comments) {
		return true
	}

	return false
}

// SetComments gets a reference to the given string and assigns it to the Comments field.
func (o *WritableRoutingPolicyRuleRequest) SetComments(v string) {
	o.Comments = &v
}

func (o WritableRoutingPolicyRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WritableRoutingPolicyRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["index"] = o.Index
	toSerialize["action"] = o.Action
	if !IsNil(o.MatchIpAddress) {
		toSerialize["match_ip_address"] = o.MatchIpAddress
	}
	toSerialize["routing_policy"] = o.RoutingPolicy
	if !IsNil(o.MatchCommunity) {
		toSerialize["match_community"] = o.MatchCommunity
	}
	if o.MatchCustom != nil {
		toSerialize["match_custom"] = o.MatchCustom
	}
	if o.SetActions != nil {
		toSerialize["set_actions"] = o.SetActions
	}
	if !IsNil(o.MatchIpv6Address) {
		toSerialize["match_ipv6_address"] = o.MatchIpv6Address
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Comments) {
		toSerialize["comments"] = o.Comments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WritableRoutingPolicyRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"index",
		"action",
		"routing_policy",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWritableRoutingPolicyRuleRequest := _WritableRoutingPolicyRuleRequest{}

	err = json.Unmarshal(data, &varWritableRoutingPolicyRuleRequest)

	if err != nil {
		return err
	}

	*o = WritableRoutingPolicyRuleRequest(varWritableRoutingPolicyRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "index")
		delete(additionalProperties, "action")
		delete(additionalProperties, "match_ip_address")
		delete(additionalProperties, "routing_policy")
		delete(additionalProperties, "match_community")
		delete(additionalProperties, "match_custom")
		delete(additionalProperties, "set_actions")
		delete(additionalProperties, "match_ipv6_address")
		delete(additionalProperties, "description")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "comments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWritableRoutingPolicyRuleRequest struct {
	value *WritableRoutingPolicyRuleRequest
	isSet bool
}

func (v NullableWritableRoutingPolicyRuleRequest) Get() *WritableRoutingPolicyRuleRequest {
	return v.value
}

func (v *NullableWritableRoutingPolicyRuleRequest) Set(val *WritableRoutingPolicyRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWritableRoutingPolicyRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWritableRoutingPolicyRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWritableRoutingPolicyRuleRequest(val *WritableRoutingPolicyRuleRequest) *NullableWritableRoutingPolicyRuleRequest {
	return &NullableWritableRoutingPolicyRuleRequest{value: val, isSet: true}
}

func (v NullableWritableRoutingPolicyRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWritableRoutingPolicyRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
